# The name of this file should be `action.yml` , `action.yaml` or `Dockerfile`.
# Should be run only on macOS or Ubuntu.

name: "Check Code Style"
desciption: "Check files for correct code style"

inputs:
  buildifier-version:
    description: "Version of 'buildifier' to install"
    required: false
    default: '5.1.0'

runs:
  using: "composite"
  steps:
    - name: Install clang-format-13 if Ubuntu
      if: ${{ runner.os == 'Linux' }}
      run: |
        # Install Clang 13 (including clang-format-13) through LLVM's preferred mechanism:
        #   https://apt.llvm.org/
        wget https://apt.llvm.org/llvm.sh 
        chmod +x llvm.sh
        sudo ./llvm.sh 13
        rm ./llvm.sh
        sudo apt-get install clang-format-13
        sudo rm -rf /var/lib/apt/lists/*
        # Remove existing symlink to clang-format and replace it.
        sudo rm /etc/alternatives/clang-format
        sudo ln -s /usr/bin/clang-format-13 /etc/alternatives/clang-format
      shell: bash

    # On macOS we should install clang-format.
    - name: Install clang-format-13 if macOS
      if: ${{ runner.os == 'macOS' }}
      run: |
        # TODO(benh): is 'brew' not in PATH on macOS like it is not in
        # the PATH for Linux? If so, where does GitHub install 'brew'
        # on a macOS runner?
        brew install clang-format@13
      shell: bash

    - name: Check all .cc , .h, .proto files for correct code style
      run: |
        chmod +x ${{ github.action_path }}/check_style_of_all_files.sh
        ${{ github.action_path }}/check_style_of_all_files.sh
      shell: bash

    - name: Install buildifier for .bzl files (macOS)
      if: ${{ runner.os == 'macOS' }}
      run: brew install buildifier@${{ inputs.buildifier-version }}
      shell: bash

    - name: Install buildifier for .bzl files (Linux)
      if: ${{ runner.os == 'Linux' }}
      run: /home/linuxbrew/.linuxbrew/bin/brew install buildifier@${{ inputs.buildifier-version }}
      shell: bash

    - name: Check all .bzl, .bazel files for correct code style
      run: |
        chmod +x ${{ github.action_path }}/check_style_bzl.sh
        ${{ github.action_path }}/check_style_bzl.sh
      shell: bash

    - name: Run YAPF to test if Python code is correctly formatted
      uses: AlexanderMelde/yapf-action@master
      with:
        args: --verbose --exclude '**/submodules/**'
